#! /bin/sh

start() {
    echo "Loading misc modules..."
    modprobe hello
    insmod /lib/modules/$(uname -r)/faulty.ko $* || exit 1
    echo "OK"
}

stop() {
    echo "Unloading misc modules..."
    rmmod hello || exit 1
    rmmod faulty || exit 1
    echo "OK"
}

restart() {
    echo "Reloading misc modules"
    stop
    start
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart | reload)
        restart
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|reload}"
    exit 1
esac

exit $?
