#! /bin/sh

start() {
    echo "Loading aesdchar module..."
    aesdchar_load
    echo "OK"
}

stop() {
    echo "Unloading aesdchar module..."
    aesdchar_unload
    echo "OK"
}

restart() {
    echo "Reloading aesdchar module"
    stop
    start
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart | reload)
        restart
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|reload}"
    exit 1
esac

exit $?
